name: countdown
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.2 
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  tray_manager: ^0.5.0
  fl_heatmap: ^0.4.5
  flutter_timer_countdown: ^1.0.7
  lottie: ^3.1.2
  shared_preferences: ^2.5.3
  http: ^1.4.0
  flutter_advanced_drawer: ^1.5.0
  flutter_svg: ^2.0.10+1
  local_notifier: ^0.1.6
  board_datetime_picker: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: huawei
      fonts: 
        - asset: assets/fonts/HarmonyOS_Sans_SC_Thin.ttf
          weight: 100
        - asset: assets/fonts/HarmonyOS_Sans_SC_Light.ttf
          weight: 300
        - asset: assets/fonts/HarmonyOS_Sans_SC_Regular.ttf
          weight: 400
        - asset: assets/fonts/HarmonyOS_Sans_SC_Medium.ttf
          weight: 500
        - asset: assets/fonts/HarmonyOS_Sans_SC_Bold.ttf
          weight: 700
        - asset: assets/fonts/HarmonyOS_Sans_SC_Black.ttf
          weight: 900